name: maho
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #ui
  glassmorphism_widgets: ^0.1.3
  google_fonts: ^3.0.1
  flutter_easyloading: ^3.0.5
  flutter_slidable: ^2.0.0
  font_awesome_flutter: ^10.1.0
  flutter_native_splash: ^2.2.9
  pull_to_refresh: ^2.0.0
  rflutter_alert: ^2.0.4
  #data
  drift: ^2.0.2+1
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.1
  freezed: ^2.1.0+1
  tuple: ^2.0.0
  json_serializable: ^6.3.1
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  #state manage
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.5+1
  #routing
  go_router: ^4.2.8
  #service
  http: ^0.13.4
  awesome_notifications: ^0.6.21
  #logger
  logger: ^1.1.0
  #util
  intl: ^0.17.0
  #web
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  drift_dev: ^2.0.2
  build_runner: ^2.1.11
  mockito: ^5.3.0
  flutter_launcher_icons: ^0.10.0
  

flutter_icons:
  ios: true
  image_path: assets/icons/icon-img.png
  min_sdk_android: 21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/login_bg.png
    - assets/images/setting_bg.png
    - assets/images/task_bg.png
    - assets/icons/icon-img.png
    - assets/splash/bg.png
    - assets/splash/icon.png
    - assets/splash/icon_android12.png
  